## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
import numpy as np
list=np.random.randint(1,10,20)
result=np.where((list>=3) & (list<=8),list*(-1),list)
print(result)

[-7 -4 -7 -4 -3 -8  9 -5 -8 -6 -6  9 -4 -5  1 -8 -6 -3 -8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
import numpy as np
list=np.random.randint(1,10,20)
print(list)
result=np.where(list==list.max(),list*0,list)
print(result)

[1 4 1 9 5 4 3 5 1 1 7 2 9 4 3 1 6 2 9 2]
[1 4 1 0 5 4 3 5 1 1 7 2 0 4 3 1 6 2 0 2]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [54]:
arr = [[1, 2], [3, 4, 5]]
meshes = [np.array(subarr) for subarr in arr]
result = np.array(np.meshgrid(*meshes)).T.reshape(-1, len(arr))
for combination in result:
    print(combination)

[1 3]
[1 4]
[1 5]
[2 3]
[2 4]
[2 5]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [97]:
A = np.random.randint(1, 6, size=(8, 3))
B = np.random.randint(1, 6, size=(2, 2))
print(A)
print(B)
result_indices = []
for row in B:
    row_indices = np.any(np.isin(A, row).reshape(-1, 3), axis=1)
    result_indices.append(row_indices)

rows_indices = np.all(result_indices, axis=0)

if np.any(rows_indices):
    result = A[rows_indices]
else:
    result = None
print("Строки в A, содержащие элементы из каждой строки в B:")
print(result)


[[4 2 4]
 [4 4 1]
 [3 5 5]
 [2 2 5]
 [1 5 4]
 [1 4 1]
 [1 5 2]
 [5 1 2]]
[[1 4]
 [5 2]]
Строки в A, содержащие элементы из каждой строки в B:
[[4 2 4]
 [1 5 4]
 [1 5 2]
 [5 1 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [60]:
random_matrix = np.random.randint(1, 4, size=(10, 3))
print(random_matrix)
rows_with_unique_values = random_matrix[np.any(np.diff(random_matrix, axis=1), axis=1)]
print('\n')
print(rows_with_unique_values)

[[1 1 1]
 [3 2 3]
 [1 3 2]
 [1 1 1]
 [2 2 1]
 [2 2 1]
 [2 3 3]
 [3 3 2]
 [1 3 1]
 [2 3 3]]


[[3 2 3]
 [1 3 2]
 [2 2 1]
 [2 2 1]
 [2 3 3]
 [3 3 2]
 [1 3 1]
 [2 3 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
matrix=np.random.randint(1,3,(4,3))
print(matrix)
print('\n')
matrix_2=np.unique(matrix,axis=0,return_index=True)
print(matrix_2)

[[2 2 1]
 [1 1 1]
 [2 1 1]
 [1 2 2]]


(array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 1],
       [2, 2, 1]]), array([1, 3, 2, 0], dtype=int64))


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
#numpy
matrix=np.random.randint(0,5,(4,3))
print(matrix)
product=np.prod(matrix.diagonal()[matrix.diagonal()!=0])
print(product)
#регулярные возможности
from random import randint
matrix=[]
for i in range (4):
    line=[]
    for j in range(3):
        line.append(randint(0,5))
    matrix.append(line)
print(matrix)
product=1
for i in range(4):
    for j in range(3):
        if i==j and matrix[i][j]!=0:
            product=product*matrix[i][j]
print(product)

[[0 4 4]
 [2 4 0]
 [4 2 0]
 [1 1 0]]
4
[[4, 5, 1], [2, 0, 2], [0, 5, 1], [1, 4, 3]]
4


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [137]:
#numpy
x=np.random.randint(1,5,4)
y=np.random.randint(1,5,4)
print(f'Задают ли векторы {x} и {y} одно мультимножество : ')
print(np.array_equal(np.sort(x),np.sort(y)))
#не numpy
x=[]
y=[]
for i in range (4):
    x.append(randint(1,4))
    y.append(randint(1,4))
print(f'Задают ли векторы {x} и {y} одно мультимножество : ')
for i in range (len(x)):
    for j in range(len(y)):
        if(x[i]==y[j]):
            y.remove(y[j])
            break
if(len(y)==0):
    print(True)
else:
    print(False)

Задают ли векторы [3 1 4 4] и [4 2 1 2] одно мультимножество : 
False
Задают ли векторы [3, 3, 4, 3] и [1, 1, 1, 4] одно мультимножество : 
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [146]:
# numpy
x=np.random.randint(0,5,10)
print(x)
print("максимальный элемент, перед которыми стоит ноль - ",np.max(x[np.where(x[:-1] == 0)[0] + 1]) if np.any(x[:-1] == 0) else None)
#без numpy
x=[]
for i in range (10):
    x.append(randint(0,5))
print(x)
list_of_index = [i for i in range(len(x) - 1) if x[i] == 0]
if list_of_index:
    max_value = max(x[list_of_index[j] + 1] for j in range(len(list_of_index)))
    print("максимальный элемент, перед которыми стоит ноль - ", max_value)
else:
    print("Нулей нет")




[1 4 0 0 3 0 2 4 4 2]
максимальный элемент, перед которыми стоит ноль -  3
[5, 1, 5, 3, 2, 2, 2, 0, 0, 2]
максимальный элемент, перед которыми стоит ноль -  2


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [135]:
# numpy
x = np.random.randint(0, 3, 8)
print(x)
changes = np.flatnonzero(np.diff(x) != 0)
changes = np.append(changes, len(x) - 1)
values = x[changes]
lengths = np.diff(np.concatenate(([0], changes + 1)))
print("Значения:", values)
print("Длины серий:", lengths)
#без numpy
p = []
numbers = []
count_of_numbers = []
prev = None
counter = 0
for i in range(0, 8):
    p.append(randint(1, 5))
print(p)
for i in range(0, 8):
    if p[i] != prev:
        if prev is not None:
            numbers.append(prev)
            count_of_numbers.append(counter)
        prev = p[i]
        counter = 0
    counter += 1
if prev is not None:
    numbers.append(prev)
    count_of_numbers.append(counter)
print("Значения:",numbers)
print("Длины серий:",count_of_numbers)


[1 2 0 1 2 0 0 1]
Значения: [1 2 0 1 2 0 1]
Длины серий: [1 1 1 1 1 2 1]
[2, 3, 3, 1, 4, 3, 2, 1]
Значения: [2, 3, 1, 4, 3, 2, 1]
Длины серий: [1, 2, 1, 1, 1, 1, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [93]:
from scipy.spatial.distance import cdist
import math
def euclidean_distance_matrix_np(X, Y):
    diff = X[:, np.newaxis] - Y
    distances_squared = np.sum(diff**2, axis=-1)
    distances = np.sqrt(distances_squared)
    return distances

X = np.random.rand(100, 5)
Y = np.random.rand(50, 5)
distances_np = euclidean_distance_matrix_np(X, Y)
print(distances_np)
distances_scipy = cdist(X, Y)
print()
%timeit euclidean_distance_matrix_np(X, Y)
%timeit cdist(X, Y)
#без numpy
def euclidean_distance(x, y):
    squared_diff = [(a - b) ** 2 for a, b in zip(x, y)]
    sum_squared_diff = sum(squared_diff)
    distance = math.sqrt(sum_squared_diff)
    return distance
x=[]
y=[]
for i in range (4):
    for j in range(4):
        X[i][j]=randint(1,10)
        Y[i][j]=randint(1,10)
print(X)
print(Y)
distances = []
for x in X:
    row = []
    for y in Y:
        row.append(euclidean_distance(x, y))
    distances.append(row)
for row in distances:
    print(row)


[[0.43954375 1.06036189 0.84271259 ... 1.03083232 0.66808483 0.63835016]
 [1.023468   0.78693596 1.42110137 ... 1.04318601 0.80415903 0.85075267]
 [0.59248597 1.25277838 0.81944373 ... 1.13055732 0.78456753 0.94327441]
 ...
 [0.49056457 1.17988418 0.88969218 ... 1.13900398 0.70799434 0.70300874]
 [0.97791747 0.88255083 0.91056124 ... 1.33766415 0.85537026 0.98258557]
 [1.06368745 0.8974872  0.69769027 ... 1.11275628 0.78821878 0.66491253]]

256 µs ± 20.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
51.8 µs ± 8.19 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
[[5.00000000e+00 7.00000000e+00 6.00000000e+00 1.00000000e+00
  6.27487243e-01]
 [2.00000000e+00 8.00000000e+00 3.00000000e+00 4.00000000e+00
  7.72321270e-01]
 [7.00000000e+00 4.00000000e+00 4.00000000e+00 6.00000000e+00
  3.72560013e-01]
 [6.00000000e+00 9.00000000e+00 9.00000000e+00 8.00000000e+00
  6.88768499e-01]
 [3.80553529e-01 3.41714323e-01 8.85666298e-01 9.49967599e-01
  5.17658154e-02]
 [3.760

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [131]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [148]:
average_calories=np.mean(calorie_stats)-60
print("Насколько выше среднее количество калорий у наших конкурентов - ",round(average_calories,2),"%")

Насколько выше среднее количество калорий у наших конкурентов -  46.88 %


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [134]:
calorie_stats_sorted=np.sort(calorie_stats)
print("Отсортированный массив\n",calorie_stats_sorted)

Отсортированный массив
 [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [149]:
median_calories=np.median(calorie_stats_sorted)
print("медиану набора данных",median_calories)

медиану набора данных 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [150]:
import numpy as np
nth_percentile = 0
for i in range(1,100):
    percentile_value = np.percentile(calorie_stats, i)
    if percentile_value > 60:
        nth_percentile = i
        break
print("Наименьший процентиль, превышающий 60 калорий - ",nth_percentile)


Наименьший процентиль, превышающий 60 калорий -  4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [152]:
more_calories=np.mean(calorie_stats_sorted>60)*100
print("Процент хлопьев, в которых содержится более 60 калорий на порцию - ",round(more_calories),"%")

Процент хлопьев, в которых содержится более 60 калорий на порцию -  96


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [132]:
calorie_std=np.std(calorie_stats_sorted)
print("Стандартное отклонение - ",round(calorie_std,2),"%")

Стандартное отклонение -  19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
#Анализируя данные о калориях в различных типах хлопьев, 
#мы определили достаточное кол-во статистических данных.
#Эти данные могут помочь Mycrunch при маркетинге CrunchieMunchies, позволяя компании сравнивать свои продукты с конкурентами,
#а также использоваться для создания информационных материалов о питательной ценности CrunchieMunchies
# и подчеркивания его конкурентных преимуществ.